#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENABLE MANDATORY FRENCH LOCALE
#=================================================
ynh_script_progression --message="Enabling french system locale..." --weight=1

sed -i 's|^#\? \?\(fr_FR.UTF-8 \?.*\)$|\1|' /etc/locale.gen

#=================================================
# FIND A REDIS DATABASE
#=================================================
ynh_script_progression --message="Searching for an available Redis database..." --weight=1

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app="$app" --key=redis_db --value="$redis_db"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_app_setting_set --app="$app" --key=install_dir --value="$install_dir"
ynh_setup_source --dest_dir="$install_dir/endi"

__ynh_endi_patch_src

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================

__ynh_endi_build

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="endi.ini" --destination="$install_dir/endi.ini"

chmod 500 "$install_dir/endi.ini"
chown "$app:$app" "$install_dir/endi.ini"

#=================================================
# CREATE LOG DIRECTORY
#=================================================

mkdir "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"
chmod 750 "/var/log/$app"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

__ynh_endi_migratedb
__ynh_endi_add_admin

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add "$app" --description="enDI, logiciel de comptabilité pour CAE" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
